my_notes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('my_notess.urls')),
]

my_notess/urls.py
#Defines URL patterns for my_notes

from django.urls import path
from . import views

app_name = 'my_notess'
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #Page that shows all topics
    path('topics/', views.topics, name='topics'),
    #Notes page for a single topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #Add a new topic page
    path('new_topic/', views.new_topic, name='new_topic'),
    #Add a new note to a topic
    path('new_note/<int:topic_id>/', views.new_note, name='new_note'),
    #Edit a note
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),
]

users/urls.py
#Defines URL patterns for users

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    #Include default auth urls
    path('', include('django.contrib.auth.urls')),
    #Registration page
    path('register/', views.register, name='register'),
]

my_notess/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    #A topic that a user would like to create notes about
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        #Return string representation of the model
        return self.text

class Note(models.Model):
    #A specific note regarding a topic
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        #Return string representation of the model
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

my_notess/forms.py
from django import forms

from .models import Topic, Note

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

my_notess/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Topic, Note
from .forms import TopicForm, NoteForm


def index(request):
    # The home page for My Notes
    return render(request, 'my_notess/index.html')


@login_required
def topics(request):
    # The topics page for My Notes. Shows all topics
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'my_notess/topics.html', context)


@login_required
def topic(request, topic_id):
    # Show all notes associated with a single topic
    topic = get_object_or_404(Topic, id=topic_id)

    # Check that topic belongs to current user
    if not check_topic_owner(topic.owner, request.user):
        raise Http404

    notes = topic.note_set.order_by('-date_added')
    context = {'topic': topic, 'notes': notes}
    return render(request, 'my_notess/topic.html', context)


@login_required
def new_topic(request):
    # Add a new topic
    if request.method != 'POST':
        # No data submitted. Create a blank form
        form = TopicForm()
    else:
        # POST data submitted. Process the data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('my_notess:topics')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'my_notess/new_topic.html', context)


@login_required
def new_note(request, topic_id):
    # Add a new note to a topic
    topic = Topic.objects.get(id=topic_id)

    # Check that topic belongs to current user
    if not check_topic_owner(topic.owner, request.user):
        raise Http404

    if request.method != 'POST':
        # No data submitted. Create a blank form
        form = NoteForm()
    else:
        # Post data submitted. Process the data
        form = NoteForm(data=request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.topic = topic
            new_note.save()
            return redirect('my_notess:topic', topic_id=topic_id)

    # Display a blank or invalid form
    context = {'topic': topic, 'form': form}
    return render(request, 'my_notess/new_note.html', context)


@login_required
def edit_note(request, note_id):
    # Edit an existing note
    note = get_object_or_404(Note, id=note_id)
    topic = note.topic
    # Check that topic belongs to current user
    if not check_topic_owner(topic.owner,request.user):
        raise Http404

    if request.method != 'POST':
        # Initial request, prefill with the current note
        form = NoteForm(instance=note)
    else:
        # POST data submitted. Process the data
        form = NoteForm(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('my_notess:topic', topic_id=topic.id)

    context = {'note': note, 'topic': topic, 'form': form}
    return render(request, 'my_notess/edit_note.html', context)


def check_topic_owner(owner, user):
    # Check if topic belongs to current user.
    # If it does, return true, else return false
    return owner == user

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    #Register a new user
    if request.method != 'POST':
        #Display blank registration form
        form = UserCreationForm()
    else:
        #Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            #Log user in and redirect to home page
            login(request, new_user)
            return redirect('my_notess:index')

    #Display a blank or invalid form
    context = {'form': form}
    return render(request, 'registration/register.html', context)

my_notess/templates/my_notess/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>My Notes</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>

    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'my_notess:index' %}">My Notes</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                ara-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_notess:topics' %}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}!</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>
</html>

my_notess/templates/my_notess/edit_note.html
{% extends "my_notess/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2><a href="{% url 'my_notess:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <h4>Edit note:</h4>

    <form action="{% url 'my_notess:edit_note' note.id %}" method='post' class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-success">Save Changes</button>
        {% endbuttons %}
    </form>


{% endblock content %}

my_notess/templates/my_notess/index.html
{% extends "my_notess/base.html" %}

{% block page_header %}
    <div class="jumbotron">
        <h1 class="display-3">Take some notes!</h1>

        <p class="lead">
            This is a simple note taking app that helps big brained apes like you organize your notes on any topic.
        </p>

        {% if not user.is_authenticated %}
            <a class="btn btn-lg btn-success" href="{% url 'users:login' %}"
               role="button">Log In &raquo;</a>
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
               role="button">Register Now &raquo;</a>
        {% else %}
            <a class="btn btn-lg btn-primary" href="{% url 'my_notess:topics' %}"
               role="button">View Topics &raquo;</a>
        {% endif %}
    </div>
{% endblock page_header %}

my_notess/templates/my_notess/new_note.html
{% extends "my_notess/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
    <h2><a href="{% url 'my_notess:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <h4>Add a new note:</h4>
    <form method="post" action="{% url 'my_notess:new_note' topic.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-success">Add note</button>
        {% endbuttons %}
    </form>

{% endblock content %}

my_notess/templates/my_notess/new_topic.html
{% extends 'my_notess/base.html' %}
{% load bootstrap4 %}

{% block page_header %}
    <h2>Add a new topic:</h2>
{% endblock page_header %}

{% block content %}

<form action="{% url 'my_notess:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
        {% buttons %}
            <button name='submit' class="btn btn-success">Add topic</button>
        {% endbuttons %}
</form>

{% endblock content %}

my_notess/templates/my_notess/topic.html
{% extends 'my_notess/base.html' %}

{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
    <p>
        <a href="{% url 'my_notess:new_note' topic.id %}">Add a new note</a>
    </p>

    {% for note in notes %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ note.date_added|date:'M d, Y H:i' }}
                <small>
                    <a href="{% url 'my_notess:edit_note' note.id %}">Edit note</a>
                </small>
            </h4>
            <div class="card-body">
                {{ note.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no notes for this topic yet. Get to writing!</p>
    {% endfor %}

{% endblock content %}

my_notess/templates/my_notess/topics.html
{% extends "my_notess/base.html" %}

{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li><h4>
                <a href="{% url 'my_notess:topic' topic.id %}">{{ topic }}</a>
            </h4></li>
        {% empty %}
            <li><h4>No topics have been added yet. Get to work!</h4></li>
        {% endfor %}
    </ul>

    <h5><a href="{% url 'my_notess:new_topic' %}">Add a new topic</a></h5>

{% endblock content %}